name: CI
on:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
        with:
          version: master
      - run: zig fmt --check src build.zig

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        optimize: [Debug, ReleaseSafe, ReleaseSmall, ReleaseFast]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: mlugg/setup-zig@v1
        with:
          version: master
      - run: zig build -Doptimize=${{ matrix.optimize }}
